FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir \
    dagster \
    dagster-webserver \
    dagster-dbt \
    dagster-dlt \
    dbt-core \
    dbt-duckdb \
    dlt \
    duckdb

ENV PYTHONPATH=/app

ENV DUCKDB_PATH=/app/duck_pond/job_ads.duckdb
ENV DBT_PROFILES_DIR=/app/data_transformation

EXPOSE 3000

CMD ["dagster", "dev", "-h", "0.0.0.0", "-p", "3000", "-m", "orchestration.definitions"]
